# Jupyter Notebook How To: 

Below is a code cell. Code cells allow you to enter and run code
Run a code cell using Shift-Enter or pressing the  button in the toolbar above:

In [1]:
message = "Hello Python world!"
print(message)

Hello Python world!


There are two other keyboard shortcuts for running code:

Alt-Enter runs the current cell and inserts a new one below.
Ctrl-Enter run the current cell and enters command mode.

Its helpful to get to know the different cell running options in the Cell menu
The "Cell" menu has a number of menu items for running code in different ways. Go ahead and take a look! 

### Restarting the kernels
The kernel maintains the state of a notebook's computations. You can reset this state by restarting the kernel. This is done by clicking on the  in the toolbar above. Once you restart your kernel you will need to rerun all the cells you previously had run.

The best way to best understand Jupyter Notebooks is to play around with one! Keep going through this tutorial and feel free to raise your hand and ask any questions if something comes up or post on piazza! 

# Helpful Basic Python How To: 

Feel free to skip on to the Numpy section if you have 61A+ eqivalent python programming knowledge

### Variables
We can use variables to hold values. These variables can hold different types of values. You can use type() to see what the variable's type. 

In [2]:
x = 1.0
type(x)

float

In [3]:
x = 1
type(x)

int

In [4]:
x = "Machine Learning Decal is hella dope"
type(x)

str

In [5]:
w = 3 
y = 8
z = w + y 
print(z)

11


Try assigning a variable to the letter 'c' that's the sum of two variable '

In [ ]:
## Your answer here ## 
a = 3
b = 4
c = a + b

### Dictionaries 
Think of a dictionary as an unordered set of key: value pairs, with the requirement that the keys are unique (within one dictionary).
You can use keys to retrieve the values associated with that key. 

In [6]:
params = {"parameter1" : 1.0,
          "parameter2" : 2.0,
          "parameter3" : 3.0,}

print(type(params))
print(params)
print(params["parameter1"])
print(params["parameter2"])
print(params["parameter3"])

<class 'dict'>
{'parameter1': 1.0, 'parameter2': 2.0, 'parameter3': 3.0}
1.0
2.0
3.0


### Lists
Lists are the most commonly used data structure. Think of it as a sequence of data that is enclosed in square brackets and data are separated by a comma. Each of these data can be accessed by calling it's index value.

Lists are declared by just equating a variable to '[ ]' or list. 

In [7]:
a = [1,2,3]
print(type(a))

<class 'list'>


You can diretly assign values to a list like below: 

In [8]:
x = ['machine learning', 'data science', 'berkeley']

### Indexing
In python, Indexing starts from 0. Thus now the list x, which has two elements will have apple at 0 index and orange at 1 index.


In [9]:
x[0]

'machine learning'

You can also directly change the value of an index: 

In [10]:
x[0] = "ai buzzword!"

In [11]:
x

['ai buzzword!', 'data science', 'berkeley']

You can also use negative indices to go backwards in a list

In [12]:
x[-1]

'berkeley'

You can even have lists inside of lists, this is the same ideas of how we'd store a matrix. 

In [13]:
y = [x]

In [14]:
y

[['ai buzzword!', 'data science', 'berkeley']]

Now try and access the original list x from y! 

In [15]:
## FILL THIS IN! ##
y[0]

['ai buzzword!', 'data science', 'berkeley']

Now try and access the the word 'berkeley' from y! 

In [16]:
## FILL THIS IN ##
y[0][2]

'berkeley'

### Slicing
Indexing was only limited to accessing a single element, Slicing on the other hand is accessing a sequence of data inside the list. In other words "slicing" the list.

Slicing is done by defining the index values of the first element and the last element from the parent list that is required in the sliced list. It is written as parentlist[ a : b ] where a,b are the index values from the parent list. If a or b is not defined then the index value is considered to be the first value for a if a is not defined and the last value for b when b is not defined.

In [17]:
num = [0,1,2,3,4,5,6,7,8,9]
print(num[0:4])
print(num[4:])

[0, 1, 2, 3]
[4, 5, 6, 7, 8, 9]


In [18]:
coolio_list = [2,9,3,8,4,7,5,6]

Try and use slicing to get the list [2,9,3,8,4,7,5] or just play around with slicing and see what kind of results you get! 

In [19]:
## FILL THIS IN### 
coolio_list[2:4]

[3, 8]

### Built in List Functions


In [20]:
#Find the length
print(len(num))

#Find the min value
print(min(num))

#Find the max value
print(max(num))

#Concetate two lists 
x = [1,2,3] + [5,4,7]
print(x)

#Check if an element is in a list
1 in x

10
0
9
[1, 2, 3, 5, 4, 7]


True

### For Loops 
For loops lets you iterate through data. 

In [21]:
for x in range(4):
    print(x)

0
1
2
3


In [22]:
a = "aren't for loops fun!" 
#iterate through the sentence letter by letter
for x in a:
    print(x)

a
r
e
n
'
t
 
f
o
r
 
l
o
o
p
s
 
f
u
n
!


In [23]:
#iterate through the key value pairs from the dictionary we defined earlier
for key, value in params.items():
    print(key + " = " + str(value))

parameter1 = 1.0
parameter2 = 2.0
parameter3 = 3.0


Iterate through the the following sentence and print out every characters 

In [24]:
sentence = "I am so excited for the Data Science Decal!!!!"
## FILL THIS IN ##
for x in sentence:
    print(x)

I
 
a
m
 
s
o
 
e
x
c
i
t
e
d
 
f
o
r
 
t
h
e
 
D
a
t
a
 
S
c
i
e
n
c
e
 
D
e
c
a
l
!
!
!
!


### Define a Function
We can create helpful functions where we can save code to be reused. Let's make some helpful functions!

In [26]:
def square(x):
    return x*x 

# You can return multiple  values
def powers(x):
    return x ** 2, x ** 3, x ** 4

#You don't have to have a return value
def split_up_string(x):
    for s in x:
        print(s)

Your turn! Try and define your own function below: 

In [28]:
#Define your function here
def test(x):
    split_up_string(x);
    
test("Wow!")

W
o
w
!


# Numpy

What is Numpy and why do we use it? 

It's an awesome python package that adds support for large, multi-dimensional arrays. Really good for vector operations, matrix operations because its super parallelized so its super fast! 


Why not Python arrays? 

Python arrays has certain limitations: they don’t support “vectorized” operations like elementwise addition and multiplication, and the fact that they can contain objects of differing types mean that Python must store type information for every element, and must execute type dispatching code when operating on each element. This also means that very few list operations can be carried out by efficient C loops – each iteration would require type checks and other Python API bookkeeping.



### Importing numpy
Functions for numerical computiing are provided by a separate module called numpy which we must import.

By convention, we import numpy using the alias np.

Once we have done this we can prefix the functions in the numpy library using the prefix np.

In [30]:
# This is the de facto way to import NumPy. You probably don't want to write numpy.whatever every time
import numpy as np

### Numpy Arrays
NumPy arrays are the workhorse of the library. A NumPy array is essentially a bunch of data coupled with some metadata:

type: the type of objects in the array. This will typically be floating-point numbers for our purposes, but other types can be stored. The type of an array can be accessed via the dtype attribute.

shape: the dimensions of the array. This is given as a tuple, where element $i$ of the tuple tells you how the "length" of the array in the $i$th dimension. For example, a 10-dimensional vector would have shape (10,), a 32-by-100 matrix would have shape (32,100), etc. The shape of an array can be accessed via the shape attribute.

Let's see some examples! There are number of ways to construct arrays. One is to pass in a Python sequence (such as list or tuple) to the np.array function:

In [31]:
np.array([1, 2.3, -6])

array([ 1. ,  2.3, -6. ])

We can also easily create ordered numerical lists!

In [32]:
# Remember we zero index so you will actually get 0 to 6!
print(np.arange(7))
# Rmember the list wont include 9
print(np.arange(3, 9))

[0 1 2 3 4 5 6]
[3 4 5 6 7 8]


We can also customize these list with a third paramter that specifices step size

In [33]:
np.arange(0.0, 100.0, 10.0)

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

To create a multi-dimensional array, we'll need to nest the sequences:

In [34]:
np.array([[1, 2.3, -6], [7, 8, 9]])

array([[ 1. ,  2.3, -6. ],
       [ 7. ,  8. ,  9. ]])

Neat! 

There are also many convenience functions for constructing special arrays. Here are some that might be useful: 

In [35]:
# The identity matrix of given size
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [36]:
# A matrix with the given vector on the diagonal
np.diag([1.1,2.2,3.3])

array([[1.1, 0. , 0. ],
       [0. , 2.2, 0. ],
       [0. , 0. , 3.3]])

In [37]:
#An array of all zeros or ones with the given shape
np.zeros((8,4)), np.ones(3)

(array([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]), array([1., 1., 1.]))

In [38]:
# An array with a given shape full of a specified value
np.full((3,4), 2.1)

array([[2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1]])

In [39]:
# A random (standard normal) array with the given shape
np.random.randn(5,6)

array([[ 0.34783901, -1.1670932 ,  0.49306929, -0.46607913, -0.98819319,
        -0.694444  ],
       [-1.0018764 ,  0.53121125, -0.02767806,  0.42782544, -1.44664583,
         2.09207965],
       [-2.00506906,  0.65446705, -0.29019734, -0.61578607,  0.66754427,
        -0.6996726 ],
       [ 0.34577489, -0.98559539, -0.58450743,  0.1927178 ,  0.50958875,
         1.93324567],
       [ 0.82560928,  0.69854517,  0.16354866,  0.61956354,  1.22933495,
         0.7468422 ]])

Okay your turn! In the cell belows try and create:


-A diagonal matrix with values from 1-20 (try and create this and only type one number!)

In [50]:
#Your answer here
x = []
for i in np.arange(1, 21):
    x += [i]
np.diag(x)

array([[ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0

Okay now let's suppose we have some data in an array so we can start doing stuff with it.


In [44]:
A = np.random.randn(10,5); x = np.random.randn(5)
A

array([[-0.57302115,  1.13116341,  0.1739534 ,  1.35249093, -0.87108389],
       [ 0.25345602, -0.0149542 ,  0.88595439,  0.05347607,  0.60239681],
       [ 0.13143091,  0.83891097, -0.15289138, -0.34736188,  1.09724385],
       [-2.96835951,  0.11543912,  1.3612456 , -0.65348685,  0.89426202],
       [-0.88037568, -0.3791484 ,  0.63770495,  0.98425965,  1.66364904],
       [ 0.32795159, -1.13383595, -0.68554235, -0.05951755,  1.34656387],
       [-1.03720325,  0.70971181,  0.62086945, -0.21474333,  0.7944224 ],
       [-2.0892365 ,  0.43867522,  0.34091238,  1.13515846,  0.19476066],
       [ 0.61035576, -0.91898153, -0.51915933, -1.5009361 ,  0.7010261 ],
       [-0.01647253,  0.60181028, -0.09300933,  0.10293969,  0.73046561]])

One useful thing that NumPy lets us do efficiently is apply the same function to every element in an array. You'll often need to e.g. exponentiate a bunch of values, but if you use a list comprehension or map with the builtin Python math functions it may be really slow. Instead just write

In [45]:
# log, sin, cos, etc. work similarly
np.exp(A)

array([[0.56381948, 3.09926012, 1.19000011, 3.8670461 , 0.4184977 ],
       [1.28847071, 0.98515706, 2.42529796, 1.05493175, 1.82649132],
       [1.14045911, 2.31384576, 0.85822293, 0.7065496 , 2.99589749],
       [0.05138754, 1.12236618, 3.90104941, 0.52022865, 2.44553036],
       [0.41462711, 0.68444404, 1.89213336, 2.6758301 , 5.27853733],
       [1.38812177, 0.32179649, 0.50381691, 0.94221899, 3.84419367],
       [0.35444459, 2.03340517, 1.86054498, 0.80674848, 2.21316231],
       [0.12378161, 1.55065159, 1.40623003, 3.11166657, 1.21502015],
       [1.84108627, 0.39892513, 0.59502055, 0.22292139, 2.01582008],
       [0.9836624 , 1.82542034, 0.911185  , 1.10842456, 2.076047  ]])

We can take the sum/mean/standard deviation/etc. of all the elements in an array:

In [46]:
np.sum(x), np.mean(x), np.std(x)

(0.5110793726626963, 0.10221587453253926, 0.6635424434511338)

You can also specify an axis over which to compute the sum if you want a vector of row/column sums (again, sum here can be replaced with mean or other operations):

In [47]:
# Create an array with numbers in the range 0,...,3 (similar to the normal Python range function,
# but it returns a NumPy array) and then reshape it to a 2x2 matrix
B = np.arange(4).reshape((2,2))

# Original matrix, column sum, row sum
B, np.sum(B, axis=0), np.sum(B, axis=1)

(array([[0, 1],
        [2, 3]]), array([2, 4]), array([1, 5]))

### Linear Algebra
By now we have a pretty good idea of how data is stored and accessed within NumPy arrays. But we typically want to do something more "interesting", which for our purposes usually means linear algebra operations. Fortunately NumPy has good support for such routines. Let's see some examples!

In [48]:
# Matrix-vector product. The dimensions have to match, of course
A.dot(x)
# Note that in Python3 there is also a slick notation A @ x which does the same thing

array([-1.58012921,  0.53477186, -0.7120126 , -3.18202255, -0.46415042,
        1.21786056, -1.70560774, -2.65378095,  1.32736289, -0.61455758])

In [49]:
# Transpose a matrix
A.T

array([[-0.57302115,  0.25345602,  0.13143091, -2.96835951, -0.88037568,
         0.32795159, -1.03720325, -2.0892365 ,  0.61035576, -0.01647253],
       [ 1.13116341, -0.0149542 ,  0.83891097,  0.11543912, -0.3791484 ,
        -1.13383595,  0.70971181,  0.43867522, -0.91898153,  0.60181028],
       [ 0.1739534 ,  0.88595439, -0.15289138,  1.3612456 ,  0.63770495,
        -0.68554235,  0.62086945,  0.34091238, -0.51915933, -0.09300933],
       [ 1.35249093,  0.05347607, -0.34736188, -0.65348685,  0.98425965,
        -0.05951755, -0.21474333,  1.13515846, -1.5009361 ,  0.10293969],
       [-0.87108389,  0.60239681,  1.09724385,  0.89426202,  1.66364904,
         1.34656387,  0.7944224 ,  0.19476066,  0.7010261 ,  0.73046561]])

Now that you're familiar with numpy feel free to check out the documentation and see what else you can do! Documentation can be found here: https://docs.scipy.org/doc/

## Excercises 
Lets try out all the new numpy stuff we just learned! Even if you have experience in numpy we suggest trying these out. 

1) Create a vector of size 10 containing zeros 

In [59]:
## FILL IN YOUR ANSWER HERE ##
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Now change the fith value to be 5 

In [60]:
## FILL IN YOUR ANSWER HERE ##
v[4] = 5
print(v)

[0. 0. 0. 0. 5. 0. 0. 0. 0. 0.]


3) Create a vector with values ranging from 10 to 49

In [61]:
## FILL IN YOUR ANSWER HERE ##
u = np.arange(10, 50)
print(u)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4) Reverse the previous vector (first element becomes last)

In [64]:
## FILL IN YOUR ANSWER HERE ##
print(np.flip(u))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


5) Create a 3x3 matrix with values ranging from 0 to 8. Create a 1D array first and then resshape it. 

In [52]:
## FILL IN YOUR ANSWER HERE ##
M = np.arange(0, 9).reshape((3, 3))
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6) Create a 3x3x3 array with random values

In [56]:
## FILL IN YOUR ANSWER HERE ##
N = np.random.randn(3, 3)
print(N)

[[ 0.19654311 -0.20861193  0.24147371]
 [-0.55098408 -0.69977207  0.56260221]
 [-1.35973205 -0.5685323   0.29560707]]


7) Create a random array and find the sum, mean, and standard deviation

In [58]:
## FILL IN YOUR ANSWER HERE ##
print(np.sum(N), np.mean(N), np.std(N))

-2.09140632782886 -0.23237848086987334 0.579629121086175
